frontend:
  build: ./frontend
  volumes:
    - ./frontend:/usr/src
  ports:
    - "8080:8080"
  links:
    - backend
  environment:
    - RACK_ENV=development

backend:
  build: ./backend
  volumes:
    - ./backend:/usr/src
  ports:
    - "8081:8081"
  environment:
    - RACK_ENV=development